### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/dds2atf#8]
Hello @renaun ,
My name is Fil and I’m from Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project? I see there were some issues filed by the community years ago, but we (Adobe) never responded :(

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project?

Thanks for any info.

-Fil

**Comment by filmaj** [comment]
Ping @adobe/flash - wondering if anyone can help me figure out answers to my questions above?

**Comment by CodeAndWeb** [comment]
It would be useful to update this project from time to time to the newest ATF format.
Was at least 1 format update after the project was uploaded.

**Comment by filmaj** [comment]
I have not heard anything from this project so it will be archived.
